FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  sample_app.py /home/myapp/
EXPOSE 5000
CMD python3 /home/myapp/sample_app.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  sample_app.py /home/myapp/
EXPOSE 5000
CMD python3 /home/myapp/sample_app.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  sample_app.py /home/myapp/
EXPOSE 5000
CMD python3 /home/myapp/sample_app.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  sample_app.py /home/myapp/
EXPOSE 5000
CMD python3 /home/myapp/sample_app.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  sample_app.py /home/myapp/
EXPOSE 5000
CMD python3 /home/myapp/sample_app.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  sample_app.py /home/myapp/
EXPOSE 5000
CMD python3 /home/myapp/sample_app.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  sample_app.py /home/myapp/
EXPOSE 5000
CMD python3 /home/myapp/sample_app.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  sample_app.py /home/myapp/
EXPOSE 5000
CMD python3 /home/myapp/sample_app.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  sample_app.py /home/myapp/
EXPOSE 5000
CMD python3 /home/myapp/sample_app.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  sample_app.py /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/sample_app.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  sample_app.py /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/sample_app.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  sample_app.py /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/sample_app.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  sample_app.py /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/sample_app.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  sample_app.py /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/sample_app.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  sample_app.py /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/sample_app.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  sample_app.py /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/sample_app.py
